version: '3.8'
services:
  zookeeper:
    image: bitnami/zookeeper:3
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'

  kafka:
    image: bitnami/kafka:3
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: transit
      POSTGRES_PASSWORD: transit
      POSTGRES_DB: transitdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  gateway_service:
    build: ./gateway_service
    depends_on:
      - location_service
      - real_time_api_service
    ports:
      - '8000:8000'
    env_file:
      - .env

  location_service:
    build: ./location_service
    depends_on:
      - postgres
      - kafka
    ports:
      - '8001:8000'
    env_file:
      - .env

  real_time_api_service:
    build: ./real_time_api_service
    ports:
      - '8002:8000'
    env_file:
      - .env

  safety_threat_detection_service:
    build: ./safety_threat_detection_service
    ports:
      - '8003:8000'
    env_file:
      - .env

  analytics_service:
    build: ./analytics_service
    ports:
      - '8004:8000'
    env_file:
      - .env

  user_reports_service:
    build: ./user_reports_service
    depends_on:
      - postgres
    ports:
      - '8005:8000'
    env_file:
      - .env

volumes:
  postgres_data:
